---

controller_credentials:
- name: gitlab
  description: Credentials for GitLab
  organization: Default
  credential_type: Source Control
  inputs:
    username: person
    password: password
- name: hashivault
  description: HashiCorp Vault Secret Lookup example using token auth
  organization: Default
  credential_type: HashiCorp Vault Secret Lookup
  inputs:
    url: https://vault.example.com:8243
    token: token
    cacert: "{{ lookup('ansible.builtin.file', '/path/to/ca-certificates.crt') }}"
    api_version: v2
- name: localuser
  description: Machine Credential example with become_method input
  credential_type: Machine
  inputs:
    username: localuser
    password: password
    become_method: sudo

controller_projects:
- name: controller Config
  organization: Default
  scm_branch: master
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ansible/tower-example.git
  notification_templates_error:
  - Slack_for_testing
git_creds: 'aoyawale_test'
git_org: 'Default'
git_name: 'aoyawale config as code'
git_url: 'git@github.com:aoyawale/devspaces_ansible.git'
aap_hostname: 
aap_username:
aap_password:
controller_username: "{{ aap_username | default(omit, true) }}"
controller_password: "{{ aap_password | default(omit, true) }}"
controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
controller_playbook: 'aap_config.yml'
request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
controller_host: "{{ aap_hostname | default(omit, true) }}"
validate_certs: "{{ aap_validate_certs | default(omit) }}"
  
github_repo_token:
github_repo_org:
github_repo_name:
github_repo_desc:
github_repo_status:
github_repo_state:

controller_templates:
- name: Survey Template with vars
  job_type: run
  inventory: Demo Inventory
  execution_environment: my_exec_env
  survey_enabled: true
  survey: "{{ lookup('template', 'template_surveys/basic_survey.json') | regex_replace('\\n', '') }}"
  project: controller Config
  playbook: helloworld.yml
  credentials:
  - Demo Credential
  extra_vars: "{{ survey_extra_vars }}"
  notification_templates_error:
  - Slack_for_testing
- name: No Survey Template no vars
  job_type: run
  inventory: Demo Inventory
  project: controller Config
  playbook: helloworld.yml
  credentials:
  - Demo Credential
  survey: {}
  extra_vars: "{{ empty_master_vars }}"
  notification_templates_error:
  - Slack_for_testing
