---

controller_credentials:
- name: Github Credentials
  description: Credentials for Github
  organization: Default
  credential_type: Source Control
  inputs:
    username: person
    password: password
      #ssh_key_data: "{{ lookup('file', '/tmp/id_rsa') }}"
      #ssh_key_unlock: "passphrase"
controller_projects:
- name: AAP Config as coode Project
  organization: Default
  scm_branch: main
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: git@github.com:aoyawale/devspaces_ansible.git

controller_templates:
- name: Create Credentials
  job_type: run
  inventory: Demo Inventory
  project: config_code
  playbook: aap_credentials.yml
  credentials:
  - Demo Credential
  survey: {}
  #extra_vars: "{{ empty_master_vars }}"
- name: Create Project
  job_type: run
  inventory: Demo Inventory
  project: config_code
  playbook: aap_projects.yml
  credentials:
  - Demo Credential
  survey: {}
- name: Create Job Templates
  job_type: run
  inventory: Demo Inventory
  project: config_code
  playbook: aap_templates.yml

controller_workflows:
  - name: AAP Configuration As Code Workflow
    description: Workflow to create different AAP items
    extra_vars: ''
    survey_enabled: false
    allow_simultaneous: false
    ask_variables_on_launch: false
    inventory:
    limit:
    scm_branch:
    ask_inventory_on_launch: false
    ask_scm_branch_on_launch: false
    ask_limit_on_launch: false
    destroy_current_nodes: false
    webhook_service: ''
    webhook_credential:
    organization: Default
    schedules: []
    simplified_workflow_nodes:
      - all_parents_must_converge: false
        identifier: node101
        unified_job_template: Create Credential
        credentials: []
        success_nodes:
          - node201
        failure_nodes: []
        always_nodes: []
      - identifier: node201
        unified_job_template: Create project
        success_nodes:
          - node301
      - all_parents_must_converge: false
        identifier: node301
        unified_job_template: Create Job template
        credentials: []
        success_nodes: []
        failure_nodes: []
        always_nodes: []
    notification_templates_started: []
    notification_templates_success: []
    notification_templates_error: []
    notification_templates_approvals: []
    survey_spec: {}

git_creds: 'aoyawale_test'
git_org: 'Default'
git_name: 'aoyawale config as code'
git_url: 'git@github.com:aoyawale/devspaces_ansible.git'
aap_hostname: 
aap_username:
aap_password:
controller_username: "{{ aap_username | default(omit, true) }}"
controller_password: "{{ aap_password | default(omit, true) }}"
controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
controller_playbook: 'aap_config.yml'
request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
controller_host: "{{ aap_hostname | default(omit, true) }}"
validate_certs: "{{ aap_validate_certs | default(omit) }}"
  
github_repo_token:
github_repo_org:
github_repo_name:
github_repo_desc:
github_repo_status:
github_repo_state:

