#SPDX-License-Identifier: MIT-0
---
# defaults file for app_git

controller_projects:
- name: controller Config
  organization: Default
  scm_branch: master
  scm_clean: 'no'
  scm_delete_on_update: 'no'
  scm_type: git
  scm_update_on_launch: 'no'
  scm_url: https://github.com/ansible/tower-example.git


github_repo_token:
github_repo_org:
github_repo_name:
github_repo_desc:
github_repo_status:
github_repo_state:
