#SPDX-License-Identifier: MIT-0
---
# tasks file for app_git

  - name: Create a Github repository
  community.general.github_repo:
    access_token: "{{ github_repo_token }}"
    organization: "{{ github_repo_org }}"
    name: "{{ github_repo_name }}"
    description: "{{ github_repo_desc }}"
    private: "{{ github_repo_status }}"
    state: "{{ github_repo_state }}"
    force_defaults: false
  register: result
