---
- name: Create AAP Credentials
  hosts: localhost
  connection: local
  vars:
    controller_hostname:
    controller_username:
    controller_password:
    controller_validate_certs: 'false'
  pre_tasks:
    - name: Include vars from platform_configs directory
      ansible.builtin.include_vars:
        dir: ./vars
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
  roles:
    - {role: infra.controller_configuration.credentials, when: controller_credentials is defined}
